# Generated by Django 2.2 on 2020-10-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semirest_tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
